config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'stores#index'
	#前端
	resources :stores do
		member do
			get :take
		end
	end
	#商家端
	namespace :mystore do
		root 'settings#index'
		resources :categories
		resources :products
		resources :settings
	end
	#站方管理員
	namespace :superadmin do
		root 'stores#index'
		resources :stores
		resources :store_categories
		resources :store_products
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	#驗證價格不能是英文, 不能小於0
	validates_numericality_of :price, :only_integer => true, :greater_than_or_equal_to => 0
	#驗證商品名稱為必填
	validates :name, presence: 'true'
end

app/controllers/mystore/products_controller.rb
class Mystore::ProductsController < ApplicationController
	def show
		session[:sid] = params[:id]
		@products = StoreProduct.where(store_id: params[:id])
	end
	def new
		@product = StoreProduct.new
		@category = StoreCategory.all
	end
	def create
		@product = StoreProduct.new(product_params)
		@category = StoreCategory.all
		if @product.save
			flash[:notice] = "#{@product.name}Save"
			redirect_to new_mystore_product_path
		else
			render :new
		end
	end

	private
	def product_params
		params.require(:store_product).permit(:store_id, :name, :price, :desc, :category)
	end
end

app/controllers/superadmin/base_controller.rb
class Superadmin::BaseController < ApplicationController
	#要操作superadmin內的所有controller都需要先驗證, 且帳號要有admin的權限
	before_action :login_required, :required_admin! 
	def required_admin!
    redirect_to root_url, notice: '你沒有 admin 權限' unless current_user && current_user.admin?
  end
  def required_store!
  	@store = Store.find_by(id: params[:id])
  	redirect_to superadmin_stores_path, notice: '沒有這筆商家存在' unless @store.present?
  end
end

app/controllers/superadmin/products_controller.rb
class Superadmin::ProductsController < Superadmin::BaseController
	def index
		session[:now_add] = nil
		@products = Product.where(store_id: session[:sid])
	end
	def new
		@product = Product.new
	end
	def create
		if session[:now_add].blank?
			session[:now_add] =[]
		end
		@product = Product.new(product_params)
		if @product.Save
			flash[:notice] = "#{@product.name} Save"
			redirect_to new_superadmin_product_url
			session[:now_add] << @product
		else
			flash[:notice] = "Warning"
			redirect_to new_superadmin_product_url
		end
	end

	private
	def product_params
		params.require(:product).permit(:store_id, :name, :price, :desc)
	end
end

app/controllers/superadmin/store_categories_controller.rb
class Superadmin::StoreCategoriesController < Superadmin::BaseController
	def index
		@store_categories = StoreCategory.all
	end
	def new
		@store_category = StoreCategory.new
	end
	def create
		@store_category = StoreCategory.new(store_category)
		if @store_category.save
			flash[:notice] = "#{@store_category.title} Save"
			redirect_to superadmin_store_categories_path
		else
			flash[:notice] = "#{@store_category.title} Error"
			redirect_to superadmin_store_categories_path
		end
	end

	private
	def store_category
		params.require(:store_category).permit(:store_id, :title, :anchor)
	end
end

app/controllers/superadmin/store_products_controller.rb
class Superadmin::StoreProductsController < Superadmin::BaseController
	def index
		session[:now_add] = nil
		@store_products = StoreProduct.where(store_id: session[:sid])
	end
	def new		
		@store_product = StoreProduct.new
		@store_category = StoreCategory.all
	end
	def create
		if session[:now_add].blank?
			session[:now_add] =[]
		end
		@store_product = StoreProduct.new(product_params)
		@store_category = StoreCategory.all
		if @store_product.save
			flash[:notice] = "#{@store_product.name}Save"
			redirect_to new_superadmin_store_product_url
			session[:now_add] << @store_product
		else
			render :new
			#redirect_to new_superadmin_store_product_url
		end
	end

	private
	def product_params
		params.require(:store_product).permit(:store_id, :name, :price, :desc, :category)
	end
end

app/controllers/superadmin/stores_controller.rb
class Superadmin::StoresController < Superadmin::BaseController
	before_action :required_store!, only: [:show, :edit, :update]
	def index
		@stores = Store.all
	end
	def new
		@store = Store.new
	end
	def create
		@store = Store.new(store_params)
		if @store.save
			redirect_to superadmin_stores_path
		else
			render :new
		end
	end
	def edit; end

	def update
		if @store.update(store_params)
			redirect_to superadmin_store_path(params[:id])
		else
			render :edit
		end
	end
	def show
		# 因為在商家頁時,會有新增產品的需求, 所以用一個session去記住現在是哪間商家.
		session[:sid] = @store.id
		@products = StoreProduct.where(store_id: params[:id])
	end

	private
	def store_params
		params.require(:store).permit(:name, :user_id, :address, :zip, :tel, :power, :status)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
	def now_add
		unless session[:now_add].blank?
			render 'now_add'
		end
	end
end

app/views/superadmin/products/index.html.erb
<%= render 'superadmin/share/menu' %>
<div class="container">
	<div class="row">
		Action =>
		<%= link_to '新增商品', new_superadmin_product_path %> | 
		<%= link_to 'Back Store', superadmin_store_path(session[:sid]) %>
	</div>
</div>	
<hr>
<div class="container">
	<div class="row">
		<table class="table table-hover">
			<tr>
				<td>sid</td>
				<td>餐點名稱</td>
				<td>價格</td>
				<td>描述</td>
			</tr>
			<% @products.each do |p| %>
				<tr>
					<td><%= p.store_id %></td>
					<td><%= p.name %></td>
					<td><%= p.price %></td>
					<td><%= p.desc %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/superadmin/products/new.html.erb
<%= render 'superadmin/share/menu' %>
<div class="container">
	<div class="row">
		Action =>
		<%= link_to 'Back Menu', superadmin_products_path %>
		<%= link_to 'Back Store', superadmin_store_path(session[:sid]) %>
	</div>
</div>	
<hr>
<div class="container">
	<div class="row">
		<%= bootstrap_form_for [:superadmin, @product] do |f| %>
		<%= f.hidden_field :store_id, value: session[:sid] %>
		<%= f.text_field :name %>
		<%= f.text_field :price %>
		<%= f.text_area :desc %>
		<%= f.submit 'submit' %>
		<% end %>
	</div>
</div>
<%= now_add %>