config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'stores#index'
	#前端
	resources :stores do
		member do
			get :take
		end
	end
	#商家端
	namespace :mystore do
		root 'settings#index'
		resources :categories
		resources :products
		resources :settings
	end
	#站方管理員
	namespace :superadmin do
		root 'stores#index'
		resources :stores
		resources :store_categories
		resources :store_products
	end
end

app/models/store.rb
class Store < ActiveRecord::Base
	belongs_to :user
	as_enum :power, 免費商家: 0, 付費商家: 1
	as_enum :status, 店面裝潢中: 0, 網店營運: 1
	#驗證價格不能是英文, 不能小於0
	validates_numericality_of :zip, :tel, :user_id, :only_integer => true, :greater_than_or_equal_to => 0
	#驗證為必填
	validates :address, :name, presence: 'true'
	#驗證電話號碼長度
	validates_length_of :tel, minimum: 7, maximum: 11
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController	
	before_action :required_store!, only: [:show]
	before_action :login_required, only: [:take]
	def index
		@stores = Store.all
	end
	def new
		@store = Store.new
	end
	def create
		@store = Store.new(store_params)
		@store.user_id = 0
		if @store.save
			redirect_to stores_url
		else
			render :new
		end
	end
	def show
		@store = Store.find_by(id: params[:id])
		@products = StoreProduct.where(store_id: params[:id])
	end
	def take
		#先判斷是否登入, 先判斷這筆資料是否已經存在, 如果存在則不寫入.
		@check = StoreTake.find_by(user_id: current_user.id, store_id: params[:id])
		unless @check.blank?
			flash[:notice] = "你已申請過領回, 站方人員將會盡快與您聯繫, 或直接來信告知站方"
			redirect_to store_path(params[:id]) and return
		end
		@take_info = StoreTake.new(user_id: current_user.id, store_id: params[:id], status: '1')
		@take_info.save
		flash[:notice] = "已送出申請, 站方人員將會與您聯繫"
		redirect_to store_path(params[:id])
	end

	private
	def store_params
		params.require(:store).permit(:name , :address, :zip, :tel, :power, :status)
	end
end

app/controllers/superadmin/base_controller.rb
class Superadmin::BaseController < ApplicationController
	#要操作superadmin內的所有controller都需要先驗證, 且帳號要有admin的權限
	before_action :login_required, :required_admin! 
	def required_admin!
    redirect_to root_url, notice: '你沒有 admin 權限' unless current_user && current_user.admin?
  end
  def required_store!
  	@store = Store.find_by(id: params[:id])
  	redirect_to superadmin_stores_path, notice: '沒有這筆商家存在' unless @store.present?
  end
end

app/controllers/superadmin/products_controller.rb
class Superadmin::ProductsController < Superadmin::BaseController
	def index
		session[:now_add] = nil
		@products = Product.where(store_id: session[:sid])
	end
	def new
		@product = Product.new
	end
	def create
		if session[:now_add].blank?
			session[:now_add] =[]
		end
		@product = Product.new(product_params)
		if @product.Save
			flash[:notice] = "#{@product.name} Save"
			redirect_to new_superadmin_product_url
			session[:now_add] << @product
		else
			flash[:notice] = "Warning"
			redirect_to new_superadmin_product_url
		end
	end

	private
	def product_params
		params.require(:product).permit(:store_id, :name, :price, :desc)
	end
end

app/controllers/superadmin/store_categories_controller.rb
class Superadmin::StoreCategoriesController < Superadmin::BaseController
	def index
		@store_categories = StoreCategory.all
	end
	def new
		@store_category = StoreCategory.new
	end
	def create
		@store_category = StoreCategory.new(store_category)
		if @store_category.save
			flash[:notice] = "#{@store_category.title} Save"
			redirect_to superadmin_store_categories_path
		else
			flash[:notice] = "#{@store_category.title} Error"
			redirect_to superadmin_store_categories_path
		end
	end

	private
	def store_category
		params.require(:store_category).permit(:store_id, :title, :anchor)
	end
end

app/controllers/superadmin/store_products_controller.rb
class Superadmin::StoreProductsController < Superadmin::BaseController
	def index
		session[:now_add] = nil
		@store_products = StoreProduct.where(store_id: session[:sid])
	end
	def new		
		@store_product = StoreProduct.new
		@store_category = StoreCategory.all
	end
	def create
		if session[:now_add].blank?
			session[:now_add] =[]
		end
		@store_product = StoreProduct.new(product_params)
		@store_category = StoreCategory.all
		if @store_product.save
			flash[:notice] = "#{@store_product.name}Save"
			redirect_to new_superadmin_store_product_url
			session[:now_add] << @store_product
		else
			render :new
			#redirect_to new_superadmin_store_product_url
		end
	end

	private
	def product_params
		params.require(:store_product).permit(:store_id, :name, :price, :desc, :category)
	end
end

app/controllers/superadmin/stores_controller.rb
class Superadmin::StoresController < Superadmin::BaseController
	before_action :required_store!, only: [:show, :edit, :update]
	def index
		@stores = Store.all
	end
	def new
		@store = Store.new
	end
	def create
		@store = Store.new(store_params)
		if @store.save
			redirect_to superadmin_stores_path
		else
			render :new
		end
	end
	def edit; end

	def update
		if @store.update(store_params)
			redirect_to superadmin_store_path(params[:id])
		else
			render :edit
		end
	end
	def show
		# 因為在商家頁時,會有新增產品的需求, 所以用一個session去記住現在是哪間商家.
		session[:sid] = @store.id
		@products = StoreProduct.where(store_id: params[:id])
	end

	private
	def store_params
		params.require(:store).permit(:name, :user_id, :address, :zip, :tel, :power, :status)
	end
end

app/helpers/stores_helper.rb
module StoresHelper

end

app/views/superadmin/stores/_form.html.erb
<%= render 'superadmin/share/menu' %>
<hr>
<div class="container">
	<div class="row">
		<%= bootstrap_form_for [:superadmin, @store]  do |f| %>				
		<%= f.select :status, enum_option_pairs(Store, :status) %>
		<%= f.text_field :name %>
		<%= f.text_field :user_id %>
		<%= f.select :power, enum_option_pairs(Store, :power) %>		
		<%= f.text_field :address %>
		<%= f.text_field :zip %>
		<%= f.text_field :tel %>
		<%= f.submit 'submit' %>
		<% end %>
	</div>
</div>

app/views/superadmin/stores/edit.html.erb
<div class="container">
	<div class="row">
		Store nav =>
		<%= link_to 'Back', superadmin_store_path(@store) %>
	</div>
</div>	
<%= render 'form' %>

app/views/superadmin/stores/index.html.erb
<%= render 'superadmin/share/menu' %>
<div class="container">
	<div class="row">
		<%= link_to 'New', new_superadmin_store_path, class: 'btn btn-primary' %>
		<hr>
		<table class="table table-hover">
			<tr>
				<td>店家名稱</td>
				<td>所屬用戶</td>
				<td>室內電話</td>
			</tr>
			<% @stores.each do |item| %>
			<tr>
				<td><%= link_to item.name, superadmin_store_path(item) %></td>
				<td><%= item.user_id %></td>
				<td><%= item.tel %></td>
			</tr>
			<% end %>
		</table>
	</div>
</div>

app/views/superadmin/stores/show.html.erb
<%= render 'superadmin/share/menu' %>
<div class="container">
	<div class="row">
		Nav =>
		<%= link_to '菜單分類', superadmin_store_categories_path %> | 
		<%= link_to '商家菜單', superadmin_store_products_path %> | <br>
		Action =>
		<%= link_to '資訊修改', edit_superadmin_store_path(@store) %> | 
	</div>
</div>	
<hr>
<div class="container">
	<div class="row">
		商家名:<%= @store.name %>
	</div>
</div>
<hr>
<div class="container">
	<div class="row">
	<h4>產品列表</h4>
		<table class="table table-hover">
			<tr>
			  <td>產品名稱</td>
			  <td>價格</td>
			  <td>描述</td>
			</tr>		
			<% @products.each do |p| %>
		  	<tr>
				  <td><%= p.name %></td>
				  <td><%= p.price %></td>
				  <td><%= p.desc %></td>
				</tr>
			<% end %>
		</table>
	</div>
</div>