config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'stores#index'
	#前端
	resources :stores do
		member do
			get :take
		end
	end
	#商家端
	namespace :mystore do
		root 'settings#index'
		resources :categories
		resources :products
		resources :settings
	end
	#站方管理員
	namespace :superadmin do
		root 'stores#index'
		resources :stores
		resources :store_categories
		resources :store_products
	end
end

app/controllers/mystore/products_controller.rb
class Mystore::ProductsController < ApplicationController
	def show
		session[:sid] = params[:id]
		@products = StoreProduct.where(store_id: params[:id])
	end
	def new
		@product = StoreProduct.new
		@category = StoreCategory.all
	end
	def create
		@product = StoreProduct.new(product_params)
		@category = StoreCategory.all
		if @product.save
			flash[:notice] = "#{@product.name}Save"
			redirect_to new_mystore_product_path
		else
			render :new
		end
	end

	private
	def product_params
		params.require(:store_product).permit(:store_id, :name, :price, :desc, :category)
	end
end

app/controllers/mystore/settings_controller.rb
class Mystore::SettingsController < ApplicationController
	def index
		@settings = Store.where(user_id: current_user.id)
	end
	def edit
		@setting = Store.find_by(id: params[:id])
	end
	def update
		@setting = Store.find_by(id: params[:id])
		if @setting.update(mystore_params)
			redirect_to mystore_settings_path
		else
			render :edit
		end
	end

	private
	def mystore_params
		params.require(:store).permit(:status, :name, :address, :zip, :tel)
	end
end

app/views/mystore/settings/edit.html.erb
<hr>
<div class="container">
	<div class="row">
		<%= bootstrap_form_for @setting, url: mystore_setting_path(@setting) do |f| %>
		<%= f.text_field :name %>
		<%= f.select :status, enum_option_pairs(Store, :status) %>
		<%= f.text_field :address %>
		<%= f.text_field :zip %>
		<%= f.text_field :tel %>
		<%= f.submit 'submit' %>
		<% end %>
	</div>
</div>

app/views/mystore/settings/index.html.erb
我擁有的商家<br>
<% @settings.each do |f| %>
<%= link_to f.name, mystore_product_path(f.id) %>
<%= link_to 'edit', edit_mystore_setting_path(f) %>
<hr>
<% end %>
<hr>
希望按下edit時, 他可以跳出一個框框, 帶出這間店的資訊＆可以修改.