config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'stores#index'
	#前端
	resources :stores do
		member do
			get :take
		end
	end
	#商家端
	namespace :mystore do
		root 'settings#index'
		resources :categories
		resources :products
		resources :settings
	end
	#站方管理員
	namespace :superadmin do
		root 'stores#index'
		resources :stores
		resources :store_categories
		resources :store_products
	end
end

app/views/common/_menu.html.erb
會員中心
<%= link_to 'logout', destroy_user_session_path, method: :delete %>
<%= current_user.email %>
<%= 
if current_user.admin?
	controller.class.to_s.include?('Superadmin')? link_to('前台', root_path) : link_to('管理後台', superadmin_root_path)
end
%>

app/views/common/_navtop.html.erb
會員中心
<%= link_to 'logout', destroy_user_session_path, method: :delete %>
<%= current_user.email %>
<%= 
if current_user.admin?
	controller.class.to_s.include?('Superadmin')? link_to('前台', root_path) : link_to('管理後台', superadmin_root_path)
end
%>

app/views/common/_store_menu.html.erb
商家設定
<%= link_to 'logout', destroy_user_session_path, method: :delete %>
<%= 
if current_user.admin?
	controller.class.to_s.include?('Superadmin')? link_to('前台', root_path) : link_to('管理後台', superadmin_root_path)
end
%>

app/views/common/_store_navtop.erb
商家管理
<%= link_to '我的商店', mystore_settings_path %>
<%= link_to '商品管理', '#' %>
<%= link_to 'logout', destroy_user_session_path, method: :delete %>
<%= 
if current_user.admin?
	controller.class.to_s.include?('Superadmin')? link_to('前台', root_path) : link_to('管理後台', superadmin_root_path)
end
%>